name: Sedstart local

on:
  workflow_dispatch:

jobs:
  sedstart:
    runs-on: ubuntu-latest
    steps:
      - name: Running Sedstart
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.SEDSTART_KEY }}
          project_id: 364
          test_id: 1629
          profile_id: 616
          browser: chrome
          headless: false
          environment: QA
