name: Sedstart local
on:
  workflow_dispatch:
jobs:
  sedstart:
    runs-on: ubuntu-latest
    steps:
    - name: Running Sedstart
      uses: sedstart/runlocal@v1
      with:
        api_key: 42c49268-69fb-413d-ba04-40dd4ea19230
        project_id: 
        suite_id: 363
        profile_id: 801
        browser: chrome
        environment: QA
        
