name: Sedstart Prod

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_PROD }}
          project_id: 543
          test_id: 4333
          profile_id: 896
          browser: chrome
          headless: false
