name: Run SedStart Test

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY }}
          project_id: 418
          test_id: 1937
          profile_id: 848
          browser: chrome
          headless: false
          environment: QA
